Repository AoTTG-2/AoTTG-2, pull requests merged in 2020-06, with the labels that each got.

#186 Version Manager
  Assets/AoTTG 2.unity
  Assets/Editor.meta
  Assets/Editor/VersionFormatterTest.cs
  Assets/Editor/VersionFormatterTest.cs.meta
  Assets/Scripts/FengGameManagerMKII.cs
  Assets/Scripts/FengGameManagerMKII.cs.meta
  Assets/Scripts/UI/Menu/Lobby.cs
  Assets/Scripts/UI/Menu/Lobby.cs.meta
  Assets/Scripts/UI/UiHandler.cs
  Assets/Scripts/UI/UiHandler.cs.meta
  Assets/Scripts/VersionFormatter.cs
  Assets/Scripts/VersionFormatter.cs.meta
  Assets/Scripts/VersionManager.cs
  Assets/Scripts/VersionManager.cs.meta
  Assets/Version Manager.asset
  Assets/Version Manager.asset.meta
Labels: Development Team, Enhancement, Low Priority

#187 Hotfix Version Manager
  Assets/Scripts/VersionManager.cs
Labels: Development Team, Enhancement, Low Priority

#180 #164 Implement new GameCursor class
  Assets/AoTTG 2.unity
  Assets/Resources/InputManagerController.prefab
  Assets/Resources/PlayerTitan.prefab
  Assets/Scripts/Characters/Human/Hero.cs
  Assets/Scripts/Characters/Titan/Attacks/GrabAttack.cs
  Assets/Scripts/Characters/Titan/Attacks/JumpAttack.cs
  Assets/Scripts/Characters/Titan/PlayerTitan.cs
  Assets/Scripts/Characters/Titan/TITAN_EREN.cs
  Assets/Scripts/Characters/Titan/TITAN_SETUP.cs
  Assets/Scripts/EventManager.cs
  Assets/Scripts/FengGameManagerMKII.cs
  Assets/Scripts/Room/LevelTriggerHint.cs
  Assets/Scripts/Settings/InputCode.cs
  Assets/Scripts/Settings/custom_inputs.cs
  Assets/Scripts/UI/Camera/CAMERA_TYPE.cs
  Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs
  Assets/Scripts/UI/CameraMode.cs
  Assets/Scripts/UI/CameraMode.cs.meta
  Assets/Scripts/UI/CursorMode.cs
  Assets/Scripts/UI/CursorMode.cs.meta
  Assets/Scripts/UI/GameCursor.cs
  Assets/Scripts/UI/GameCursor.cs.meta
  Assets/Scripts/UI/InGame/InGameMenu.cs
  Assets/Scripts/UI/InGame/InGameUi.cs
  Assets/Scripts/UI/InGame/RegistrationCounter.cs
  Assets/Scripts/UI/InGame/RegistrationCounter.cs.meta
  Assets/Scripts/UI/InGame/SpawnMenu.cs
  Assets/Scripts/UI/Menu/CreateRoom.cs
  Assets/Scripts/UI/Menu/Lobby.cs
  Assets/Scripts/UI/Menu/MainMenu.cs
  Assets/Scripts/UI/Menu/MenuManager.cs
  Assets/Scripts/UI/Menu/MenuManager.cs.meta
  Assets/Scripts/UI/Menu/Singleplayer.cs
  Assets/Scripts/UI/UiNavigationElement.cs
Labels: Development Team, Enhancement

#200 #182 default textured houses
  Assets/AoTTG 2.unity
  Assets/Material/GROUND.mat
  Assets/Material/PureMetal.mat
  Assets/Material/WALL.mat
  Assets/Material/house 1.mat
  Assets/Material/house.mat
  Assets/Material/houseBothSide.mat
  Assets/Material/unnamed.mat
  Assets/Resources/shaders/Double Sided.shader
  Assets/Resources/shaders/Double Sided.shader.meta
  Assets/Scene/scene/Colossal Titan.unity
  Assets/Scene/scene/The City I.unity
Labels: Bug

#201 #95 trost gamemode eren rock is frozen
  AoTTG-2.sln
  Assets/Scripts/Characters/Titan/TITAN_EREN.cs
Labels: Bug
